### ISSUE TITLE
otbr Docker images are outdated

### ISSUE THREAD

**Issue by simonlingoogle** [openthread/ot-commissioner#109]
**Problems:**

- Both `openthread/otbr` and `openthread/otbr_arm32v7l_raspbian` are not update to date. 
  - **Docker images should be automatically updated and always kept up to date.**
- Should use the same image name `openthread/otbr` for multiple CPU architectures

**Comment by jwhui** [comment]
See:

- https://github.com/openthread/ot-br-posix/issues/452

- https://github.com/openthread/ot-br-posix/issues/289
