### ISSUE TITLE
master builds failing due to Socket::Reset API removal

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-commissioner#113]
#110 removes `Socket::Reset` API.

However, #45 makes use of `Socket::Reset` API.
https://github.com/openthread/ot-commissioner/blob/49c4773156a0e9b4a7320b0bbce32190ef42ec6b/src/library/coap_secure.hpp#L110

Builds on master are failing after merging #45.

**Comment by simonlingoogle** [comment]
We should have a check to avoid it happen again. @wgtdkp
