### ISSUE TITLE
libreadline7 is obsolete in Ubuntu 20.04

### ISSUE THREAD

**Issue by alexbarcelo** [openthread/ot-commissioner#154]
I am using Ubuntu 20.04 and realized that everything is working smoothly **except** the installation of libreadline7 ([here](https://github.com/openthread/ot-commissioner/blob/4beb6cb822a4b074fa5250128ba87c31d613ca05/script/bootstrap.sh#L62)).

I manually changed that line into `libreadline8` and all the script seems to be working as expected, and the subsequent build is successful. I assume that simply changing libreadline7 into libreadline8 is not desirable, as that may break some other Linux distros or supported platform (maybe Raspberry Pi / Debian / Raspberry Pi OS still has libreadline7 as default? I haven't checked).

Either improving the script or adding some comment in the documentation (I am following [this](https://openthread.io/guides/commissioner/build)) might be an improvement.

**Comment by wgtdkp** [comment]
@alexbarcelo Thanks for raising this issue. I am trying if we can get rid of the libreadlineX-dev package (it looks like stale dependencies not needed anymore). I will create a PR after verifying this on multiple platforms.
