### ISSUE TITLE
Joiner IID computation bug

### ISSUE THREAD

**Issue by krbvroc1** [openthread/ot-commissioner#168]
Via code inspection... please correct me if I am wrong.

The Thread Spec says the Joiner IID is computed by taking the SHA256 hash and <b>flipping</b> the 'u' bit.

In ComputeJoinerId, the code erroneously performs an OR rather than XOR.

https://github.com/openthread/ot-commissioner/blob/ce6b1180459d2533f730b3effee626efee16b9a3/src/library/commissioner_impl.cpp#L102-L104

In GetJoinerID, the calculation is correct.
https://github.com/openthread/ot-commissioner/blob/ce6b1180459d2533f730b3effee626efee16b9a3/src/library/joiner_session.cpp#L92-L94

**Comment by wgtdkp** [comment]
please notice that `Joiner ID` and `Joiner IID` are different things.

**Comment by krbvroc1** [comment]
> please notice that `Joiner ID` and `Joiner IID` are different things.

What is the purpose of this distinction? Joiner IID is defined in the spec and Joiner ID is just made up by someone? Joiner IID is unique and Joiner ID can theoretically have a collision of two devices?

**Comment by jwhui** [comment]
> What is the purpose of this distinction? Joiner IID is defined in the spec and Joiner ID is just made up by someone? Joiner IID is unique and Joiner ID can theoretically have a collision of two devices?

The Thread Specification defines both Joiner ID and Joiner Interface Identifier (Joiner IID). In short, the Joiner IID is the Joiner's link-local IPv6 Interface Identifier. The Joiner IID is derived from the Joiner ID by inverting the "u" bit of the MAC Extended Address.

See Section 8.10.1.9 and Section 8.10.2.5 of the [Thread 1.1.1 Specification](https://www.threadgroup.org/support#specifications) for more details.

**Comment by krbvroc1** [comment]
Thank you for correcting me and pointing me to the appropriate Thread section.
