### ISSUE TITLE
add a script to build ot-commissioner

### ISSUE THREAD

**Issue by bukepo** [openthread/ot-commissioner#192]
OpenThread projects maintain scripts like `script/build` or `script/cmake-build` for easily building the projects. Could this project add such a script?

**Comment by Mellobrainbox** [comment]
> OpenThread projects maintain scripts like `script/build` or `script/cmake-build` for easily building the projects. Could this project add such a script?

Yes under the law that it's only a bolowd app to use under belling statistic

**Comment by EskoDijk** [comment]
@bukepo I tried it just now; there's a `script/build` available - this issue can be closed?

**Comment by jwhui** [comment]
Fixed by #200
