### ISSUE TITLE
Thread Commissioning App Delay

### ISSUE THREAD

**Issue by rohithanayady** [openthread/ot-commissioner#204]
When using the Thread Commissioning App for the commissioning it takes more (5-10 minutes) to add new device. What will be the reason for this delay? The version of the app is **Version 1.01.11**.What will be the reason for this ?

**Comment by jwhui** [comment]
@rohithanayady , which Thread Commissioning App are you using? Are you using the [release from this project](https://github.com/openthread/ot-commissioner/releases/tag/v0.0.1)? Or the one from the Play Store?

**Comment by rohithanayady** [comment]
The one from play store

**Comment by jwhui** [comment]
> The one from play store

As mentioned in [my response to your e-mail](https://github.com/openthread/openthread/blob/main/src/cli/README_DATASET.md#active), can you try using [this release](https://github.com/openthread/ot-commissioner/releases/tag/v0.0.1)? Note that the app found in Play Store is not the same implementation.

**Comment by rohithanayady** [comment]
I have checked the *dataset active*  from the joiner console.It shows the
same network as created by the border router + leader with same
masterkey,same pan id and same channel.But still it shows the state as
*detached*

**Comment by jwhui** [comment]
> I have checked the *dataset active* from the joiner console.It shows the same network as created by the border router + leader with same masterkey,same pan id and same channel.But still it shows the state as *detached*

I just [responded to your e-mail](https://openthread.io/guides/pyspinel/sniffer). Again, please keep the conversation in one place.

**Comment by jwhui** [comment]
Consolidating conversation to openthread-users.
