### ISSUE TITLE
Android App: Failed to import io.openthread.commissioner.XXX

### ISSUE THREAD

**Issue by Olivier-STMicro** [openthread/ot-commissioner#213]
When building the Android App, I have issues like this:

```
...\ot-commissioner\android\openthread_commissioner\service\src\main\java\io\openthread\commissioner\service\ThreadCommissionerServiceImpl.java:36: error: cannot find symbol
import io.openthread.commissioner.ChannelMask;
                                 ^
  symbol:   class ChannelMask
  location: package io.openthread.commissioner
```

I have such errors on every import of io.openthread.commissioner.XXX (ex: "io.openthread.commissioner.ChannelMask")
Do you know what I'm missing?

I have looked in app build.gradle file but I don't see dependency for io.openthread.commissioner.

Thanks for your help

**Comment by OLmmyT** [comment]
I have seen the guidelines on https://github.com/openthread/ot-commissioner/blob/main/android/BUILDING.md

**Comment by wgtdkp** [comment]
Does https://github.com/openthread/ot-commissioner/blob/main/android/BUILDING.md solve your issue?

**Comment by OLmmyT** [comment]
This is still on-going. I have seen in the guidelines that the build is only possible on Linux and MacOS, whereas I was on Windows (in Git bash). I'm currently trying on Linux (Ubuntu).

That's a pity that it doesn't work on Windows. Is there any chance to run the scripts on Linux, build it on Linux and then copy the project to my Windows machine? I would be interested to be able to work on Windows. This is more convenient for me.

Thanks

**Comment by wgtdkp** [comment]
Yes the commissioner library works on only Linux and Mac OS. It is possible to add support for Windows as there isn't any Linux/MacOS-specific dependencies, but we currently don't have a plan on it.

**Comment by OLmmyT** [comment]
Is it possible to build it on Windows thanks to cygwin? I have already tried with "git bash" (since I have it on my machine) but it doesn't work.

**Comment by wgtdkp** [comment]
I have no much experience with cygwin, but you may try [Linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/).

**Comment by jwhui** [comment]
Closing stale issue.
