### ISSUE TITLE
Cannot resolve symbol 'ByteArray'

### ISSUE THREAD

**Issue by huan-haha** [openthread/ot-commissioner#214]
When I compiled the OpenThread Commissioner Android project for the first time, an error occurred: Cannot resolve symbol 'ByteArray'. What is the reason? What should I do? Thank you very much for your answer.
![20210701172534](https://user-images.githubusercontent.com/69808663/124102910-5cfc0500-da93-11eb-9d7e-661723b9acdb.jpg)

**Comment by wgtdkp** [comment]
I can build the app without issues for my pixel phone.
Did you follow https://github.com/openthread/ot-commissioner/blob/main/android/README.md to build the shared libraries before open the android project?

**Comment by huan-haha** [comment]
> I can build the app without issues for my pixel phone.
> Did you follow https://github.com/openthread/ot-commissioner/blob/main/android/README.md to build the shared libraries before open the android project?

Thank you. I did not build successfully on Windows. I don't know if it can be successfully built on Ubuntu and then copied to Windows for use.

**Comment by sookah** [comment]
Same issue here 
![image](https://user-images.githubusercontent.com/5146726/124451511-bf038580-dd85-11eb-89d5-9beefd8636be.png)

**Comment by wgtdkp** [comment]
1. OT Commissioner doesn't support Windows.
2. Follow https://github.com/openthread/ot-commissioner/blob/main/android/BUILDING.md to build.

**Comment by jwhui** [comment]
Closing stale issue.
