### ISSUE TITLE
Fix for macOS on ARM

### ISSUE THREAD

**Issue by motters** [openthread/ot-commissioner#222]
Update catch2 dependance to support apple silicon.

Currently catch2 is detached at [d10b9bd](https://github.com/catchorg/Catch2/commit/d10b9bd) (Nov 2019) whereas catch2 was updated to support apple silicon at [a25c1a2](https://github.com/catchorg/Catch2/commit/a25c1a2 )(24 July 2020)

**Comment by wgtdkp** [comment]
@motters Thanks for reporting this issue, I submitted https://github.com/openthread/ot-commissioner/pull/224 to remove `Catch2`. Will you help verify if everything works on Apple silicon now?

**Comment by motters** [comment]
Can confirm everything now works fine, (compiled, test ran successfully, installed, functional).

Slight error on running `sudo ninja install` this comes up `sudo: ldconfig: command not found`; nothing important though i don't think for macos.
