### ISSUE TITLE
mdns IPv6 resolve issue on Wlan0 interface 

### ISSUE THREAD

**Issue by thousif-e5** [openthread/ot-commissioner#239]
Not able to resolve ipv6 address in avahi-browse tool.
![Screenshot from 2023-10-19 22-27-53](https://github.com/openthread/ot-commissioner/assets/138437412/b919d62f-2b8a-476d-851b-9d3b11da9f08)

**Comment by wgtdkp** [comment]
Hi,

This doesn't seem to be related with the ot-commissioner, right?

How did you set up the `_elementuredev._udp` service? Please you share your end device and Border Router log?

**Comment by jwhui** [comment]
Dup of https://github.com/openthread/ot-br-posix/issues/2074
