### ISSUE TITLE
My apologies for posting a question as an issue..does ot-commissioner support Matter DAC attestation and NOC initialization?

### ISSUE THREAD

**Issue by jni2000** [openthread/ot-commissioner#241]
I am new to the community and trying to find our if the current ot-commissioner support Matter DAC attestation and NOC initialization or not. I did not find any Q&A nor community forum board. Please can anyone help answering. Thanks a lot.

**Comment by jwhui** [comment]
The OpenThread project only implements protocols specified in the Thread Specification. For Matter related protocols, check out https://github.com/project-chip/connectedhomeip

**Comment by jwhui** [comment]
The OpenThread project does not implement any Matter-specific technologies.
