### ISSUE TITLE
Support alternative mdns implementations

### ISSUE THREAD

**Issue by jwhui** [openthread/ot-commissioner#31]
We support choosing between alternative mdns implementations in openthread/ot-br-posix using the ["--with-mdns" build option](https://github.com/openthread/ot-br-posix/blob/affbbdb34b2c6743b1e83a1fd5ef50cf6e93d6ac/configure.ac#L449).

**Comment by wgtdkp** [comment]
We can even remove mdns from OT Commissioner library and let the application choose any mDNS implementation by providing a parser to parse the mDNS response into a structured [BorderAgent](https://github.com/openthread/ot-commissioner/blob/master/include/commissioner/border_agent.hpp) object.

Need to decide what is the best approach.

**Comment by wgtdkp** [comment]
close this issue because mDNS is removed from the library to CLI App. An mobile App can use native mDNS implementation.
