### ISSUE TITLE
[docs] Improve Steering Data handling usage description

### ISSUE THREAD

**Issue by edmont** [openthread/ot-commissioner#71]
The command used to allow a new MeshCoP Joiner can't be figured out from the README description in https://github.com/openthread/ot-commissioner/blob/master/src/app/cli/README.md#steering-dataset

What actually works is:

`joiner enable meshcop 0x0123456789abcdef DevicePSKd`

**Comment by wgtdkp** [comment]
@edmont It seems the `cli/README.md` is not up to date and missing meshcop joiner example. I will fix this soon. For command line usage, you can always type `help` and `help <command>` for the syntax.

**Comment by edmont** [comment]
@wgtdkp thanks!
