### ISSUE TITLE
Wrong decoding of mdns response

### ISSUE THREAD

**Issue by deimi** [openthread/ot-commissioner#92]
In [border_agent.cpp](https://github.com/openthread/ot-commissioner/blob/db8c71faee2c59dac973e201b434ba49a2bfb220/src/app/border_agent.cpp#L202)  some of the mdns txt response values are not parsed correctly. 
According to thread specification they are transmitted as raw byte values, but the ot-commissioner app interprets them as string formatted hex values. E.g. `sb`

**Comment by wgtdkp** [comment]
@deimi Thanks for raising this issue! But it seems [RFC 6763](https://tools.ietf.org/html/rfc6763#section-6) defines TXT value type to be string (the name `TXT` also indicates it). I think other data formats should be encoded as string. I will fire issue about this to threadgroup.

**Comment by deimi** [comment]
@wgtdkp 
From section [6.5. Rules for Values in DNS-SD Key/Value Pairs](https://tools.ietf.org/html/rfc6763#section-6.5)
> The value is opaque binary data.  Often the value for a particular attribute will be US-ASCII [RFC20] or UTF-8 [RFC3629] text, but it is legal for a value to be any binary data.

So as far as I understand this, it's ok that the thread standards defines some values to be transmitted as raw bytes and not as string formatted hex values.

**Comment by wgtdkp** [comment]
@deimi 
oh, I missed that! I think you are right. It seems it is fine to have binary value. Thanks! I will fix it.
